version: "3"
  
services:
        syncthing:
                container_name: Syncthing_container
                build:
                        context: .
                        dockerfile: Dockerfile.windows

                image: "synct:latest"

                ports:
                        - 10000:8080
                        - 22000:22000
                
                volumes:
                        - .\data:C:\Users\ContainerAdministrator\syncthing_data
                        - .\.config:C:\Syncthing\home\.config
                networks:
                        - syncthing_net

networks:
        syncthing_net:
                driver: nat